spring:
  profiles:
    active: local

  main:
    banner-mode: off

cloud:
  aws:
    stack:
      auto: false

logging:
  level:
    com.amazonaws.util.EC2MetadataUtils: error

ai:
  fetcher:
    playground:
      sqspoc:
        consumer:
          queues:
            dummy-creation-event:
              url: http://localhost:4566/000000000000/ai_fetcher_playground_sqspoc_queues_dummy-creation-event.fifo
